version: "3"

services:
  db:
    image: postgres:13.1
    env_file:
      - environment.env
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: "exit 0"
    volumes:
      - postgres:/var/lib/postgresql

  sidekiq:
    image: blogapp-backend
    command: 'bundle exec sidekiq'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - backend
    env_file:
      - environment.env
    restart: always

  redis:
    image: redis:6.0
    restart: always

  backend:
    image: blogapp-backend
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "9090:4000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - environment.env
    restart: always

volumes:
  postgres:
  bundle_path:
